import request from './request'
export const getCandidateList = params => request.get('/candidate/list', { params }).then(r => r.data)
export const getCandidate = id => request.get('/candidate/' + id).then(r => r.data)
export const createCandidate = data => request.post('/candidate', data).then(r => r.data)
export const submitQuestionnaire = data => request.post('/public/questionnaire', data).then(r => r.data)
export const sendQuestionnaireInvitation = data => request.post('/questionnaire-invitations', data).then(r => r.data)
export const getQuestionnaireInvitation = token => request.get('/public/questionnaires/' + encodeURIComponent(token)).then(r => r.data)
export const submitQuestionnaireInvitation = (token, data) => request.post('/public/questionnaires/' + encodeURIComponent(token), data).then(r => r.data)
export const getPublicPositions = () => request.get('/public/positions').then(r => r.data)
export const getPublicOffer = token => request.get('/public/offers/' + encodeURIComponent(token)).then(r => r.data)
export const respondToPublicOffer = (token, data) => request.post('/public/offers/' + encodeURIComponent(token) + '/response', data).then(r => r.data)
export const updateCandidate = (id, data) => request.put('/candidate/' + id, data).then(r => r.data)
export const getDuplicates = params => request.get('/candidate/duplicates', { params }).then(r => r.data)
export const createRecord = (id, type, data) => request.post('/candidate/' + id + '/records/' + type, data).then(r => r.data)
export const updateRecord = (id, type, recordId, data) => request.put('/candidate/' + id + '/records/' + type + '/' + recordId, data).then(r => r.data)
export const getWorkspace = () => request.get('/workspace').then(r => r.data)
export const getInbox = () => request.get('/inbox').then(r => r.data)
export const markInboxRead = messageId => request.put(`/inbox/${encodeURIComponent(messageId)}/read`).then(r => r.data)
export const markAllInboxRead = () => request.put('/inbox/read-all').then(r => r.data)
export const uploadAsset = (id, file, type = '简历') => {
  const form = new FormData()
  form.append('file', file)
  return request.post('/candidate/' + id + '/assets', form, { params: { type } }).then(r => r.data)
}
export const downloadAsset = (id, assetId) => request.get('/candidate/' + id + '/assets/' + assetId + '/download', { responseType: 'blob' }).then(r => r.data)
export const getAssetPreview = (id, assetId) => request.get('/candidate/' + id + '/assets/' + assetId + '/preview').then(r => r.data)
export const deleteAsset = (id, assetId) => request.delete('/candidate/' + id + '/assets/' + assetId).then(r => r.data)
export const getMailSettings = companyId => request.get('/settings/mail', { params: { companyId } }).then(r => r.data)
export const saveMailSettings = data => request.put('/settings/mail', data).then(r => r.data)
export const testMailSettings = (recipient, companyId) => request.post('/settings/mail/test', { recipient, companyId }).then(r => r.data)
export const getAuditLog = () => request.get('/audit').then(r => r.data)
